### ISSUE TITLE
certificate expired error

### ISSUE THREAD

**Issue by Ciaran1981** [cedadev/opendap-python-example#3]
I have used this script quite a bit in the past, but now it no longer works due to the following error which indicates a certificate has expired

`SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)`

which culminates in 

`SSLError: HTTPSConnectionPool(host='slcs.ceda.ac.uk', port=443): Max retries exceeded with url: /onlineca/certificate/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))`

How do I update the certificate /rectify this issue?

**Comment by watucker** [comment]
Thanks for checking that! I wasn't able to reproduce the problem so it must have been because of cached outdated trust roots. Useful to know.
